variables:
  GITHUB_REPO: $CI_PROJECT_NAME
  GITHUB_GROUP: enix
  ANSIBLE_INVENTORY: "tests/inventory"
  PYTHONUNBUFFERED: "1"
  ANSIBLE_FORCE_COLOR: "true"
  PY_COLORS: "1"

molecule:
  stage: test
  services:
    - docker:dind
  variables:
      DOCKER_BUILDKIT: 1
      DOCKER_HOST: tcp://docker:2376
      DOCKER_TLS_CERTDIR: "/certs"
      DOCKER_TLS_VERIFY: 1
      DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
      DOCKER_DRIVER: overlay2

  image: docker:24-dind
  before_script:
    - apk add --no-cache
      python3 python3-dev py3-pip gcc git curl build-base
      autoconf automake py3-cryptography linux-headers
      musl-dev libffi-dev openssl-dev openssh rsync
    - python3 -m pip install ansible molecule[docker] ansible-lint yamllint
    - docker info
    - python3 --version
    - ansible --version
    - ansible-lint --version
    - yamllint --version
    - molecule --version  

  script:
    - molecule test --all -- -vv
  tags:
    - docker-dind

.ansible_test_template: &ansible_test
  script:
    - ansible --version
# Run linters. Does not fail if no errors reported
    - ansible-lint --force-color . || true
    - yamllint -f colored . || true
    - ansible localhost -m setup
# Uncomment if your role have depends
#    - ansible-galaxy install -v -r requirements.yml
    - ansible-playbook tests/test.yml --syntax-check
    - ansible-playbook -vvv --connection=local tests/test.yml
    # - idempotence=$(mktemp)
    # - ansible-playbook -vvv --connection=local tests/test.yml | tee ${idempotence}
    # - >
    #   tail ${idempotence}
    #   | grep -q 'changed=0.*failed=0'
    #   && (echo 'Idempotence test: pass' && exit 0)
    #   || (echo 'Idempotence test: fail' && exit 1)
# This part is used to check role run.
# Add your own tests depending on your $ROLE
    # - echo "=======> Starting output tests"

# We build using (ansiblecheck)[https://hub.docker.com/r/ansiblecheck/ansiblecheck/]
# images It provide a wide variety of OS container images to test with.
# most frequent ones included here

# debian-wheezy:
#   image: ansiblecheck/ansiblecheck:debian-wheezy
#   <<: *ansible_test

debian-jessie:
  image: ansiblecheck/ansiblecheck:debian-jessie
  <<: *ansible_test

debian-stretch:
  image: ansiblecheck/ansiblecheck:debian-stretch
  <<: *ansible_test

debian-buster:
  image: registry.gitlab.com/lcaflc/ansiblecheck:debian-buster
  <<: *ansible_test

debian-bullseye:
  image: registry.gitlab.com/lcaflc/ansiblecheck:debian-bullseye
  <<: *ansible_test

debian-bookworm:
  image: registry.gitlab.com/lcaflc/ansiblecheck:debian-bookworm
  <<: *ansible_test

ubuntu-bionic:
  image: registry.gitlab.com/lcaflc/ansiblecheck:ubuntu-bionic
  <<: *ansible_test

ubuntu-focal:
  image: registry.gitlab.com/lcaflc/ansiblecheck:ubuntu-focal
  <<: *ansible_test

ubuntu-jammy:
  image: registry.gitlab.com/lcaflc/ansiblecheck:ubuntu-jammy
  <<: *ansible_test

importgalaxy:
  stage: deploy
  image: registry.gitlab.com/lcaflc/ansiblecheck:debian-bullseye
  only: 
    - main
    - master
    - tags
#  when: on_success
  before_script:
    - ansible --version
  script:
    - ansible-galaxy role import ${GITHUB_GROUP} ${GITHUB_REPO} --token ${GALAXY_API_TOKEN}

# Trigger rebuild of enix install scripts
enixinstall:
  stage: deploy
  only: 
    - tags
  trigger: 
    project: enix/install
    strategy: depend
