---
- name: Configure teleport
  ansible.builtin.template:
    dest: /etc/teleport.yaml
    src: teleport.yaml.j2
    owner: root
    group: root
    mode: 0400
    backup: true
  notify:
    - restart teleport
  tags: config

- name: Enable teleport
  ansible.builtin.service:
    name: teleport
    state: started
    enabled: true
  ignore_errors: yes
