---

- name: Install APT https transport
  apt:
    package: apt-transport-https
    update_cache: yes
    state: present

- name: Register repository signing key
  apt_key:
    url: "{{ teleport__apt_repo_key }}"
  when: teleport__apt_signing_legacy

- name: Ensire /usr/share/keyrings/ exists
  file:
    path: "/usr/share/keyrings"
    state: directory
    mode: '0755'
  when: not teleport__apt_signing_legacy

- name: Download repository signing key
  ansible.builtin.get_url:
    url: "{{ teleport__apt_repo_key }}"
    dest: /usr/share/keyrings/teleport-archive-keyring.asc
    mode: '0644'
    force: no
  when: not teleport__apt_signing_legacy

- name: Add or update Teleport's APT repository
  ansible.builtin.template:
    dest: "/etc/apt/sources.list.d/teleport.list"
    src: "teleport.list.j2"
    owner: root
    group: root
    mode: 0444
  register: apt_repo_template

- name: Remove legacy debian repository drop-in files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/sources.list.d/deb_releases_teleport_dev.list
    - /etc/apt/sources.list.d/apt_releases_teleport_dev_ubuntu.list
    - /etc/apt/sources.list.d/apt_releases_teleport_dev_debian.list

- name: Remove legacy debian repository from /etc/apt/sources.list
  apt_repository:
    repo: "{{ teleport__legacy_apt_repo }}"
    state: absent
    update_cache: yes

- name: Remove Enix.io debian repository
  apt_repository:
    repo: "{{ teleport__enix_apt_repo }}"
    state: absent
    update_cache: yes

# Task used for some migration where package was in Hold status.
# We allow to fail when package is not installed.
- name: UnHold teleport package version
  dpkg_selections:
    name: teleport
    selection: install
  ignore_errors: True

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes
  when: apt_repo_template.changed

- name: Install teleport package
  apt:
    package: "teleport"
    state: latest
    update_cache: yes
  notify:
    - restart teleport
