---

- name: Install APT https transport
  apt:
    package: apt-transport-https
    update_cache: yes
    state: present

- name: Register repository signing key
  apt_key:
    url: "{{ teleport__apt_repo_key }}"
  when: not teleport__localkey

- name: Register local repository signing key
  apt_key:
    data: "{{ lookup('file', 'teleport-pubkey.asc') }}"
  when: teleport__localkey

# - name: Register Enix.io repository signing key
#   apt_key:
#     url: "{{ teleport__enix_apt_repo_key }}"
#   when: not teleport__localkey

# - name: Register local Enix.io repository signing key
#   apt_key:
#     data: "{{ lookup('file', 'enix-teleport-pubkey.asc') }}"
#   when: teleport__localkey

- name: Install Amazon Root CA
  copy:
    src: AmazonRootCA1.pem
    dest: /etc/ssl/certs
    mode: 0444
    owner: root
    group: root
  when: teleport__localkey

- name: Add debian repository
  apt_repository:
    repo: "{{ teleport__apt_repo }}"
    state: "{{ teleport__apt_repo_status }}"
    update_cache: yes

- name: Remove legacy debian repository
  file:
    path: /etc/apt/sources.list.d/deb_releases_teleport_dev.list
    state: absent

- name: Remove legacy debian repository
  apt_repository:
    repo: "{{ teleport__legacy_apt_repo }}"
    state: absent
    update_cache: yes

- name: Add Enix.io debian repository
  apt_repository:
    repo: "{{ teleport__enix_apt_repo }}"
    state: "{{ teleport__enix_apt_repo_status }}"
    update_cache: yes

- name: UnHold teleport package version
  dpkg_selections:
    name: teleport
    selection: install

- name: Install teleport package
  apt:
    package: "teleport"
    state: latest
    update_cache: yes
