---
- name: "Restart Teleport"
  ansible.builtin.service:
    name: teleport
    state: restarted
    enabled: true
  async: "{{ not ansible_check_mode }}"
  poll: 0
  register: teleport_restart

- name: "Wait for restart"
  ansible.builtin.wait_for_connection:
    delay: 10
    sleep: 5
    timeout: 300

- name: "Check restart status"
  ansible.builtin.async_status:
    jid: "{{ teleport_restart.ansible_job_id }}"
  when: not ansible_check_mode
