---

- name: Restart teleport
  service:
    name: teleport
    state: restarted

- name: collect facts about system services
  service_facts:
  register: services_state

- name: Check if teleport failed to restart
  fail:
    msg: "Teleport service failed to restart"
  when: services_state.ansible_facts.services["teleport.service"]["status"] == "failed"



