# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "debian/buster64"
  config.vm.define "debian64" do |debian64| end

# virtualbox provider only need a base virtualbox installation on
# the local system. This is the default if no provider requested
  config.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 1
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../tests/test.yml"
    ansible.verbose = "vvv"
    ansible.become = true
    ansible.compatibility_mode = "2.0"
#    ansible.galaxy_role_file = "../requirements.yml"
    ansible.groups = {
      "test" => ["debian64"],
      }
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    # Configure cached packages to be shared between instances of the same base box.
    # More info on http://fgrehm.viewdocs.io/vagrant-cachier/usage
    config.cache.scope = :box
  end
end
