---
# handlers file for teleport

- name: reload systemd
  systemd:
    daemon_reload: yes
  ignore_errors: yes

- name: restart teleport
  service: name=teleport state=restarted
  ignore_errors: yes
