---
- name: Converge
  hosts: all

  roles:
    - role: "enix.teleport"
      #      teleport__version: 8
      teleport__agent: true
      teleport__nodename: "test.node"
      teleport__proxy: true
      teleport__proxy_public_addr: "toto.tp.com:443"
      teleport__proxy_acme: false
      teleport__proxy_acme_email: "test@toto.com"
      teleport__node: false
      # teleport__node_token: ""
      # teleport__node_server: ""
      teleport__auth: true
      teleport__auth_cluster_name: "toto.tp.com"
      teleport__ssh: true
      teleport__ssh_labels:
        tenant: toto.com
        bla: test
