FROM {{ item.image }}

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    #    supervisor \
       sudo \
       python3 \
       ca-certificates \
    && rm -rf /var/lib/apt/lists/* \
    && rm -Rf /usr/share/doc \
    && rm -Rf /usr/share/man \
    && apt-get clean

# CMD /usr/bin/supervisord
