---
- name: Prepare
  hosts: all

  tasks:
    - name: Install depends
      ansible.builtin.apt:
        name:
          - gnupg
          - locales
        state: present
        update_cache: true
